### ISSUE TITLE
Enumerable#group_by Post

### ISSUE THREAD

**Issue by sstern6** [annewchen/annewchen.github.io#18]
Hey Anne,

I really enjoyed reading your blog post.  I have never used the .group_by method before, but after reading your blog post I feel like I could use it the next time we have a challenge.  I also felt like the example in your post solidified the concepts for me.  Maybe something to try for next time, a little but more of a basic first example for a beginning programmer.  Just a thought

-Scott

**Comment by annewchen** [comment]
BELATED thanks for reading!
I remember reading this issue then forgetting to comment :(
I ended up using the example from ruby-docs. But I agree, it wasn't super easy to understand... I'm going to have to think of an easier method to replace it with.
