### ISSUE TITLE
Per Usual, this is great

### ISSUE THREAD

**Issue by cMzajac** [annewchen/annewchen.github.io#28]
really concise explanation!  I honestly think my favorite part was the summary - for some reason,
I rarely think to include those...Your examples are great as well, nothing too farfetch'd or overtly
complicated.  I'm ultra guilty(more guilty) of this, but the color scheme is a little off-putting.  I think we 
migrate our blogs and all that to a different format at some point (rumor has it anyway) so don't 
think too much on it.  Well done, as always :)

**Comment by annewchen** [comment]
sadly my colors scheme looks like an elementary schooler picked it :( 
I've never been great with picking colors and such so I'm definitely hoping those rumors are true!! Thanks for the honest review, really appreciate it! :)
